### ISSUE TITLE
Camera freezes in mobile view...

### ISSUE THREAD

**Issue by akbartus** [alemart/martins-js#3]
Hi,

Thank you for creating a really interesting webAR framework. I wanted to see its possibilities on a mobile device, but unfortunately as soon as camera is on, it freezes and nothing works. Is there a certain limitation for use on mobile devices?

**Comment by alemart** [comment]
Hi,

What's your device? What does the browser console say?

**Comment by akbartus** [comment]
> Hi,
> 
> What's your device? What does the browser console say?

Thanks for quick reply. I am using Samsung J3 Orbit phone with Android 9. I did not check the browser for errors on mobile though. In contrast it works well on desktop/notebook computers.

**Comment by alemart** [comment]
Hi,

Do you still need support? Can I help you with anything else?

**Comment by akbartus** [comment]
Hi! Sorry for coming back later. Let me test it with other devices as well and I will let you know. I did not use remote debugging yet. As for the browsers I used Android Mozilla and Chrome browsers.

**Comment by alemart** [comment]
May I still help you?

**Comment by gavan1** [comment]
same issue happens on chrome and safari for IOS on iPhones....I highly suggest you do your end to end testing as at this current state the library is not usable. Mind AR and AR.js work.

**Comment by alemart** [comment]
The engine is not yet compatible with the iPhone, but it will be. I will resume this work in the near future.
