### ISSUE TITLE
Question: how many image targets can be created

### ISSUE THREAD

**Issue by ThorstenBux** [alemart/martins-js#5]
Hi I'm working on a project where I'd need to show different content on mover 30 different images. Is this possible? Thank you 🙏

**Comment by alemart** [comment]
Hi, @ThorstenBux !

When recognizing 30 different images in a single page, consider loading your virtual elements asynchronously for performance.

If you're using three.js, read `ar.referenceImage` to distinguish between the images.

**Comment by ThorstenBux** [comment]
Hi,

Thanks for the answer. I was testing with 32 images yesterday. I didn’t scan all of them but just some random and they all worked.

I simply extended your threejs webcam demo.

Is that a false positive or do 32+ work as well?

Kind regards
Thorsten Bux

Sent from my iPhone

On 29 Jun 2024, at 11:14 AM, Alexandre Martins ***@***.***> wrote:

﻿

Hi, @ThorstenBux<https://github.com/ThorstenBux> !

When recognizing 30 different images in a single page, consider loading your virtual elements asynchronously for performance.

If you're using three.js, read ar.referenceImage to distinguish between the images.

**Comment by alemart** [comment]
I haven't set a hard limit as to how many images you can add, but those images should be highly textured and very distinct from each other.

What do the logs of the browser console say with those 32 images?

**Comment by ThorstenBux** [comment]
Hi,

According to the log output everything is working 😀.

Kind regards
Thorsten Bux

Sent from my iPhone

On 2 Jul 2024, at 2:12 PM, Alexandre Martins ***@***.***> wrote:

﻿

I haven't set a hard limit as to how many images you can add, but those images should be highly textured and very distinct from each other.

What do the logs of the browser console say with those 32 images?

**Comment by alemart** [comment]
Hi!

The logs present some numbers, sizes and percentages. Would you share with me the logs generated by your page of 32 images?

**Comment by ThorstenBux** [comment]
Hi @alemart , you could look for yourself. The logs are enabled on this link: https://d3a72zaklsvmkw.cloudfront.net/

**Comment by alemart** [comment]
The logs look good. Thanks for sharing!
