### ISSUE TITLE
CORS for image targets

### ISSUE THREAD

**Issue by ThorstenBux** [alemart/martins-js#6]
Hi,

I encountered this issue:

![image](https://github.com/alemart/martins-js/assets/16772796/25e66d53-9b74-4d5e-ad6c-7b803f64ca07)
how can I allow images from another domain to be loaded?

**Comment by alemart** [comment]
Hello,

Add the `crossorigin` attribute to your `<img>` and make sure that the server is sending appropriate CORS headers.

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
