### ISSUE TITLE
How to Map an Image to a Detected Marker

### ISSUE THREAD

**Issue by cyocun** [alemart/martins-js#9]
Thank you for the amazing WebAR Engine. I think it's a fantastic piece of work.
I would like to consult on the following point and ask how it can be achieved.
I am operating under the assumption of using Three.js.

I want to map a plane to a marker.
For example, I would like to place a red plane on top of the detected marker image, matching the marker's size (the plane's ratio will be adjusted to match the marker during implementation).

The current Three.js demo does not have such functionality, so could I see some sample code for this?

Thank you for your time and assistance.

Best regards,

**Comment by alemart** [comment]
Hello!

The XY-plane, centered at the origin of the virtual world, will be mapped to the center of the target image.

The internal matrices of the engine are normalized so that 1 virtual unit corresponds _approximately_ to `min(width, height) / 2` of the target image in the video.

If `a` is the aspect ratio of your reference image, then its size in virtual space will be `(2 * a, 2)` if `a >= 1`, or `(2, 2 / a)` otherwise. In your app, you might want to adjust this size with some extra padding.

Here is a sample code for reference:

```js
const img = document.getElementById('my-reference-image');

const aspectRatio = img.naturalWidth / img.naturalHeight;
const padding = 0.0; //0.25; // adjust as needed
const width = (2 + padding) * Math.max(aspectRatio, 1);
const height = (2 + padding) / Math.min(aspectRatio, 1);

const geometry = new THREE.PlaneGeometry(width, height);
const material = new THREE.MeshBasicMaterial({ color: 0xff0000 });
const mesh = new THREE.Mesh(geometry, material);

ar.root.add(mesh);
```

**Comment by cyocun** [comment]
Thank you for your prompt response. It is very helpful.

I find your library much easier to use compared to other webAR libraries, and I particularly like speedy-vision—it’s really cool.

I tried the reference code you provided, but the alignment seems to be off, as shown in the attached image. I would be happy if it could align as well as the green line that appears when the marker is detected, but it seems difficult to achieve.🥹
<img width="799" alt="スクリーンショット 2024-07-11 18 03 51" src="https://github.com/alemart/martins-js/assets/1397111/b8266054-13d1-4f11-a68d-fb067db61ec8">



Also, is it okay to ask other questions? If it’s better to create a separate issue for them, please let me know.

Currently, I am testing based on:
https://github.com/alemart/martins-js/blob/master/demos/hello-three/demo.js


Is it possible to get the matrix or coordinates of the group displayed in animate()? In other words, I want to display objects at the same coordinates as ar.root without adding them to ar.root.

I think this is the relevant information in the documentation, but I couldn't figure out how to obtain it😩:
https://alemart.github.io/martins-js/api/pose/

**Comment by cyocun** [comment]
> Also, is it okay to ask other questions? If it’s better to create a separate issue for them, please let me know.

> Currently, I am testing based on:
> https://github.com/alemart/martins-js/blob/master/demos/hello-three/demo.js

> Is it possible to get the matrix or coordinates of the group displayed in animate()? In other words, I want to display objects >at the same coordinates as ar.root without adding them to ar.root.

> I think this is the relevant information in the documentation, but I couldn't figure out how to obtain it😩:
> https://alemart.github.io/martins-js/api/pose/

I managed to resolve this issue myself. I found that the mix() function in the following file retrieves each matrix:
https://github.com/alemart/martins-js/blob/master/demos/assets/three-with-martins.js

Based on this, it seems detecting multiple image-trackers might be difficult, right? 🥹

Additionally, regarding the main issue of mapping a Plane to an image, I noticed that while the alignment is almost perfect in the center of the screen, there is significant misalignment when shifting up, down, left, or right. It appears as if there's a large gap between the actual video and the AR object.

Although it is not possible to obtain depth information from the camera, is there a way to reduce this misalignment?

**Comment by alemart** [comment]
Hello again!

> I tried the reference code you provided, but the alignment seems to be off, as shown in the attached image. I would be happy if it could align as well as the green line that appears when the marker is detected, but it seems difficult to achieve.

Make sure that the plane geometry is at the origin of `ar.root` and that it is scaled appropriately.

> Also, is it okay to ask other questions? If it’s better to create a separate issue for them, please let me know.

On GitHub Issues, I offer public advice and take notice of bug reports related to my projects. I also offer consulting via email, in private. In a private consultation, I can look at your project more deeply and advise you in more specific ways. I can inspect your code and suggest changes if necessary. If you prefer a more in-depth consultation, please [email me](https://github.com/alemart).

> Is it possible to get the matrix or coordinates of the group displayed in animate()? In other words, I want to display objects at the same coordinates as ar.root without adding them to ar.root.

When working with the three.js plugin, add all your virtual elements to `ar.root` and they will be aligned for you. You may optionally create sub-groups to organize your virtual elements. You need not be concerned with these matrices.

> Based on this, it seems detecting multiple image-trackers might be difficult, right?

An instance of the Image Tracker can detect multiple images with ease, but it will only track one at a time.

> Additionally, regarding the main issue of mapping a Plane to an image, I noticed that while the alignment is almost perfect in the center of the screen, there is significant misalignment when shifting up, down, left, or right. It appears as if there's a large gap between the actual video and the AR object.
> 
> Although it is not possible to obtain depth information from the camera, is there a way to reduce this misalignment?

A big part of this relies on me improving some internal calculations. For the time being, I can recommend you [these guidelines](https://alemart.github.io/martins-js/getting-started/guidelines-for-images/#other-considerations).

> I find your library much easier to use compared to other webAR libraries, and I particularly like speedy-vision—it’s really cool.

Thank you for your interest in my work.

**Comment by alemart** [comment]
Hello, @cyocun!

I have improved the calculations and submitted an update. The virtual plane is now more closely aligned to the green lines, including when you move it away from the center of the screen.

Make sure to get the [updated version](https://github.com/alemart/martins-js/tree/master/dist) from the master branch in order to test the tracking. You'll notice a better alignment.
I'm closing this issue now. Feel free to reach out again if you have further questions.

For the people who will be reading this message in the future: please refer to [these guidelines](https://alemart.github.io/martins-js/getting-started/guidelines-for-images/#other-considerations).
